### ISSUE TITLE
Crash when trying to save

### ISSUE THREAD

**Issue by omomoki** [webbben/memory-card-share#5]
Traceback (most recent call last):
  File "/home/hamu/Desktop/memory-card-share/script/main.py", line 6, in <module>
    loop = menu()
           ^^^^^^
  File "/home/hamu/Desktop/memory-card-share/script/menu.py", line 390, in menu
    menu_options[line - 1][1]()
  File "/home/hamu/Desktop/memory-card-share/script/menu.py", line 205, in reviewChanges
    api.saveMemoryCardChanges()
  File "/home/hamu/Desktop/memory-card-share/script/api_handlers.py", line 119, in saveMemoryCardChanges
    push_to_github(commitMessage)
  File "/home/hamu/Desktop/memory-card-share/script/api_handlers.py", line 241, in push_to_github
    repo.git.add(file)
  File "/home/hamu/.local/share/virtualenvs/memory-card-share-_G10XmqC/lib/python3.11/site-packages/git/cmd.py", line 800, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hamu/.local/share/virtualenvs/memory-card-share-_G10XmqC/lib/python3.11/site-packages/git/cmd.py", line 1386, in _call_process
    return self.execute(call, **exec_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hamu/.local/share/virtualenvs/memory-card-share-_G10XmqC/lib/python3.11/site-packages/git/cmd.py", line 1183, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git add /Card A/JPN/01-GAEJ-DobutsunomoriE_MURA.gci
  stderr: 'fatal: Invalid path '/Card A': No such file or directory'

**Comment by omomoki** [comment]
looks like the problem is the path in linux cant support a space in the memory card folder name
